### ISSUE TITLE
FlaredDisk problem

### ISSUE THREAD

**Issue by AlexSokoliuk** [gyoto/Gyoto#11]
Hi. Sorry for bothering you again. Today the problem is a bit more complicated. I added the metric of a tidal wormhole with constant shape function, throat radius r0 and mass r0/2 with the use of python. Additionally I created a scenario for a flared disk (both metric and scenario are attached to this letter).  But, unfortunately flared accretion disk behaves strange and does not recreate the results, similar to the Schwarzshild black hole solution. However, with the given metric for a spherically symmetric and traversable wormhole, thin accreation disk behaves as expected and ray tracing image is very similar to those, that were generated with the help of KerrKS/BL, Schwarzshild metrics. What could be wrong here? Maybe I have mistaken somewhere, but I checked the line element and christoffel symbols for a hundred of times. Thank you for your attention. It will be great if you could help me with this issue
[Simulation.zip](https://github.com/gyoto/Gyoto/files/8500588/Simulation.zip)
.

**Comment by paumard** [comment]
Dear Alex,

When reporting a problem, please try to give more details about what happens vs. what you think should happen. A copy of the terminal output of Gyoto is very often userful.

I ran gyoto on your XML file. I get three suspicious symptoms:
1- a lot of Gyoto SEVERE warnings:
SEVERE: in Worldline::IntegState.C: norm is drifting - with norm,normref= -160794 8.1349e-17 -- x1,x2,x3= 1 0.991412 62.1186

2- a few Python warnings:
./gyoto_sample_metrics.py:51: RuntimeWarning: divide by zero encountered in double_scalars
  dst[1][1][1]=-(shape-r*dshape)/(2*r**2-2*r*shape)
./gyoto_sample_metrics.py:50: RuntimeWarning: invalid value encountered in double_scalars
  dst[1][0][0]=(math.exp(2*redshift)*(r-shape)*dredshift)/r
./gyoto_sample_metrics.py:51: RuntimeWarning: invalid value encountered in double_scalars
  dst[1][1][1]=-(shape-r*dshape)/(2*r**2-2*r*shape)

and:
./gyoto_sample_metrics.py:48: RuntimeWarning: overflow encountered in double_scalars
  dredshift = aa/(r*r)
./gyoto_sample_metrics.py:51: RuntimeWarning: overflow encountered in double_scalars
  dst[1][1][1]=-(shape-r*dshape)/(2*r**2-2*r*shape)

3- finally, the integration stops with a Python error:
TypeError: bad argument type for built-in operation
In gyoto.C: Error during ray-tracing: Metric.C:204 in virtual int Gyoto::Metric::Python::christoffel(double (*)[4][4], const double*) const: Error occurred in Metric::Python::gmunu

You will need to investigate those issues on your side.
The most fundamental problem first:

2- the division by zero is worrisome. It looks like your metric diverges when r==0 and when r==shape (at least it does the way it is implemented). You should try to detect when r become very small and when r is very close to rshape and let christoffel return 1 in this case, which will stop the integration nicely. If your goal is to cross those values, you will have to revise your strategy as the code cannot numerically behave well around a division by zero.

It is possible that solving this will be enough to solve the SEVERE warnings of problem 1.

1- Gyoto SEVERE warnings should be taken seriously. The norm of the photon diverges pretty fast in this integration. This sometimes happens for legitimate reasons in numerical metrics, but in an analytical metric it should not happen and is probably the sign of a mistake in your metric of Christoffel coefficients.

3- this Python error is also a problem but may be due to the two previous issues.

Best regards, Thibaut.

**Comment by paumard** [comment]
Just for the record: those APIs where not exposed in the Python interface at the time, they are now.
