### ISSUE TITLE
At some point encounter error at the bigger resolution for user defined metric

### ISSUE THREAD

**Issue by singlefrequency** [gyoto/Gyoto#12]
Hi. Recently I installed Gyoto and successfully obtained some results for user-defined singular metrics. However, when I'm trying to increase the resolution of simulation (lets say from 64 to 128), I encounter this error:
```
TypeError: bad argument type for built-in operation
In gyoto.C: Error during ray-tracing: Metric.C:204 in virtual int Gyoto::Metric::Python::christoffel(double (*)[4][4], const double*) const: Error occurred in Metric::Python::gmunu
```
How could it be solved? In order to resolve the photon sphere, I needed higher resolution of the image. I attach the image, produced for 64x64 resolution with my metric.
![download](https://user-images.githubusercontent.com/104352184/165585325-9645b897-43c8-4b73-9cc5-ced6d251134f.png)

**Comment by paumard** [comment]
Hi,

it is likely due to a Python error in your christoffel method (the mention to gmunu at the end is deceptive, I just fixed this). I'll work on printing out more informative error messages when they occur in Python code, but I'm not there yet. Basically all Python errors currently transform into "TypeError: bad argument type for built-in operation".

While I'm looking at it, there is a trick that you can do: protect the entire body of christoffel in a try/except block. In the except branch, print the Exception and any useful information (e.g. the content of the "x" argument). Then raise the Exceptaion again:

  def christoffel(self, dst, x):
      try:
          # actually compute dst
      except Exception as e:
          print(e)
          numpy.set_printoptions(precision=20)
          raise e
      return 0

When the error will occur again, the actual error message will appear right above the generic "TypeError: bad argument type for built-in operation" block.

Once this is done you can call christoffel only on this input and don't need perform ray-tracing on the full field-of-view:

  metric=gyoto.core.Metric("Python")
  metric.set("Module", <you module>)
  metric.set("Class", <your class>)
  metric.set("Parameters", <whatever parameters you need>)
  dst = metric.christoffel(pos_where_error_occurs)

Note that the calling sequence is not what you would expect. This is because we don't call your method directly, but the Pythonized Gyoto method, which in turn calls your method. (This is also error messages are hidden).

Regards, Thibaut.


To debug this, you would first need to determine on what input does your christoffel method choke on. Running Gyoto in debug mode will spit out a lot of lines and may allow you to pin point the problem, but that may take a very long time.

**Comment by paumard** [comment]
I've actually improved error handling in Gyoto::Metric::Python so error messages will not be hidden anymore if you upgrade your installation. The trick with try/except is still useful for printing `x` in case of Exception.

**Comment by paumard** [comment]
I'm now closing this issue, come back to us if not solved.
