### ISSUE TITLE
Error while trying to profile application

### ISSUE THREAD

**Issue by ealione** [gyoto/Gyoto#14]
I compiled and installed Gyoto as normal to test if it is running fine. I then edited the Makefile to add the `-pg` flag since I wanted to figure out how many times each function is called, and in general profile the application. This caused the error seen below. Using callgrind also shows no success. 

![image](https://user-images.githubusercontent.com/5569899/175835090-52cf7dce-046d-412e-8fdd-0bf5927ef16c.png)

My edits are in the CFLAGS and CXXFLAGS

![image](https://user-images.githubusercontent.com/5569899/175835177-ca1132d6-663a-4b8b-b008-2e8d235a2a93.png)

Is this an issue other people had when trying to profile Gyoto? How should I profile it, to figure out how many times each function is called etc?

**Comment by paumard** [comment]
Thanks for your interest, I'll be interested in your test results.

I changed CFLAGS and CXXFLAGS to "-g -pg" in all Makefiles and ran "make check" without this issue. The error you report means that the XML file was not found, are you sure of the path to this file relative to where you are calling gyoto?

I think one would also need to add -pg to LDFLAGS, and even so you will probably miss a lot of calls since many things are implemented in plug-ins that are dlopened. You may have more luck with sprof or oprofile instead.

Regards, Thibaut.
