### ISSUE TITLE
Unable to install gyotoy interface

### ISSUE THREAD

**Issue by tahami111** [gyoto/Gyoto#18]
Hello,
Even after following the instructions given in README and README.gyotoy ,I am getting the following error when I call gyotoy on terminal:

(Gyotoy:6570): GLib-WARNING **: 19:02:37.175: GError set over the top of a previous GError or uninitialized memory.
This indicates a bug in someone's code. You must ensure an error is NULL before it's set.
The overwriting error message was: 
Requiring namespace 'Gdk' version '4.0', but '3.0' is already loaded
ERROR (gy_gtk_xid) /usr/lib/yorick/
  LINE: 1318  FILE: /usr/lib/yorick/i/gy_gtk.i
ERROR (gyerror) gy action received signal SIGSEGV
  LINE: 1260  FILE: /usr/lib/yorick/i/gy_gtk.i
yorick: quitting on error in batch mode

**Comment by paumard** [comment]
Thanks for your feedback. The bug is actually in yorick-gy and has been fixed there. The easy fix is to download gy_gtk.i from github: https://github.com/paumard/yorick-gy/blob/master/gy_gtk.i and place it somewhere where yorick will find it, i.e. any directory reported by `echo "get_path();" | yorick`
